# Generated by Django 3.2.3 on 2021-05-22 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claimsmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsmodel',
            name='description',
            field=models.CharField(
                max_length=2000, null=True, verbose_name='Description of Loss'),
        ),
        migrations.AddField(
            model_name='claimsmodel',
            name='isInjured',
            field=models.CharField(
                default='no', max_length=3, verbose_name='Anybody Injured?'),
        ),
        migrations.AddField(
            model_name='claimsmodel',
            name='isPoliceReported',
            field=models.CharField(
                default='no', max_length=3, verbose_name='Police Report Lodged?'),
        ),
        migrations.AddField(
            model_name='claimsmodel',
            name='location',
            field=models.CharField(
                max_length=400, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='claimsmodel',
            name='mobileNo',
            field=models.IntegerField(default=123, verbose_name='Mobile No.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimsmodel',
            name='photo',
            field=models.ImageField(
                null=True, upload_to='images/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='claimsmodel',
            name='time',
            field=models.TimeField(null=True, verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='claimsmodel',
            name='typeOfLoss',
            field=models.CharField(
                default='type1', max_length=20, verbose_name='Type of Loss:'),
        ),
        migrations.AddField(
            model_name='claimsmodel',
            name='vehicleNo',
            field=models.CharField(
                default="ABC123", max_length=10, verbose_name='Vehicle No.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimsmodel',
            name='vehicleYearMake',
            field=models.IntegerField(
                default=1996, verbose_name='Vehicle Year Make'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='vehicleModel',
            field=models.CharField(
                max_length=100, verbose_name='Vehicle Model'),
        ),
    ]
