# Generated by Django 3.2.3 on 2021-05-22 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_alter_claimsmodel_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimsmodel',
            name='photo',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='images/', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
