# Generated by Django 3.2.3 on 2021-05-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_alter_claimsmodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsmodel',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdf/', verbose_name='PDF document of Insurance cover:'),
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description of Loss'),
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='location',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='mobileNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mobile No.'),
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time'),
        ),
    ]
