# Generated by Django 3.2.3 on 2021-05-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_auto_20210522_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimsmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/images/', verbose_name='Photo'),
        ),
    ]
