# Generated by Django 3.2.3 on 2021-05-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_alter_claimsmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimsmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='isInjured',
            field=models.CharField(default='No', max_length=3, verbose_name='Anybody Injured?'),
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='isPoliceReported',
            field=models.CharField(default='No', max_length=3, verbose_name='Police Report Lodged?'),
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='typeOfLoss',
            field=models.CharField(default='Own Damage', max_length=20, verbose_name='Type of Loss:'),
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='vehicleModel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Model'),
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='vehicleNo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Vehicle No.'),
        ),
        migrations.AlterField(
            model_name='claimsmodel',
            name='vehicleYearMake',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vehicle Year Make'),
        ),
    ]
