# Generated by Django 3.2.3 on 2021-05-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_auto_20210523_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsmodel',
            name='updateStatus',
            field=models.CharField(choices=[('P', 'In Progress'), ('A', 'Accepted')], default='P', max_length=1, verbose_name='Update Status'),
            preserve_default=False,
        ),
    ]
