# Generated by Django 3.2.3 on 2021-05-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_claimsmodel_updatestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimsmodel',
            name='updateStatus',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Accepted', 'Accepted')], default='In Progress', max_length=20, verbose_name='Update Status'),
        ),
    ]
