# Generated by Django 3.2.3 on 2021-05-23 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claims', '0011_claimsmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimsmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_model', to=settings.AUTH_USER_MODEL),
        ),
    ]
