# Generated by Django 3.2.3 on 2021-05-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0012_alter_claimsmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimsmodel',
            name='user',
        ),
    ]
